import { NowPlaying, Song } from "../model.slint";
import { Text } from "../components/prelude.slint";
import { ProgressBar } from "../components/progress-bar.slint";

export component Player {
    in property <bool> autoplay;

    init => {
        NowPlaying.load_song(NowPlaying.song);
        if autoplay {
            NowPlaying.play();
        } else {
            NowPlaying.pause();
        }
    }
    height: 100%;
    width: 100%;

    VerticalLayout {
        padding-left: 36px;
        padding-right: 36px;
        alignment: start;

        Text {
            height: 48px;
            text: @tr("Now Playing");
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 20px;
        }

        HorizontalLayout {
            padding-top: 24px;
            padding-bottom: 36px;
            spacing: 36px;

            Rectangle {
                width: 250px;
                height: self.width;

                Image {
                    width: 100%;
                    height: 100%;
                    source: NowPlaying.song.cover-art;
                }
            }

            VerticalLayout {
                spacing: 24px;
                alignment: start;

                Text {
                    text: NowPlaying.song.title;
                    wrap: word-wrap;
                    font-size: 32px;
                }

                Text {
                    text: NowPlaying.song.artist;
                    wrap: word-wrap;
                    font-size: 24px;
                }

                Text {
                    text: NowPlaying.song.album;
                    wrap: word-wrap;
                    font-size: 24px;
                }
            }
        }

        ProgressBar {
            progress: NowPlaying.progress;
            duration: NowPlaying.song.duration;
        }
    }
}
