import { NowPlaying, Song } from "../model.slint";
import { Text } from "../components/prelude.slint";
import { ProgressBar } from "../components/progress-bar.slint";

export component Player inherits FocusScope {
    key-released(event) => {
        if event.text == "a" {
            if NowPlaying.is-playing {
                NowPlaying.pause();
                NowPlaying.is-playing = false;
            } else {
                NowPlaying.play();
                NowPlaying.is-playing = true;
            }
            return accept;
        }

        if event.text == "x" {
            repeat = !repeat;
            return accept;
        }

        if event.text == "y" {
            shuffle = !shuffle;
            return accept;
        }

        return reject;
    }

    in-out property<bool> shuffle;
    in-out property<bool> repeat;

    init => {
        NowPlaying.load_song(NowPlaying.song);
    }
    height: 100%;
    width: 100%;

    // Rectangle {
    //     background: @linear-gradient(45deg, #411B1B 0%, #212748 100%);
    // }

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40px;

        Image {
            x: 12px;
            y: 6px;
            width: 28px;
            height: 28px;
            source: @image-url("../assets/music.svg");
        }

        Text {
            height: 40px;
            text: @tr("Now Playing");
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 20px;
        }

        Image {
            x: parent.width - 40px - 12px;
            y: 0px;
            width: 40px;
            height: 40px;
            source: @image-url("../assets/battery.svg");
        }

    }

    VerticalLayout {
        padding-top: 40px;
        padding-left: 24px;
        padding-right: 24px;
        padding-bottom: 24px;
        alignment: start;

        HorizontalLayout {
            spacing: 36px;
            padding-top: 24px;
            padding-bottom: 30px;

            Rectangle {
                width: 250px;
                height: 250px;

                Image {
                    width: 100%;
                    height: 100%;
                    source: NowPlaying.song.cover-art;
                }
            }

            VerticalLayout {
                spacing: 24px;
                alignment: start;

                Text {
                    text: NowPlaying.song.title;
                    wrap: word-wrap;
                    font-size: 28px;
                }

                Text {
                    text: NowPlaying.song.artist;
                    wrap: word-wrap;
                    font-size: 24px;
                }

                Text {
                    text: NowPlaying.song.album;
                    wrap: word-wrap;
                    font-size: 24px;
                }
            }
        }

        ProgressBar {
            progress: NowPlaying.progress;
            duration: NowPlaying.song.duration;
        }
    }

    VerticalLayout {
        alignment: end;
        padding-bottom: 26px;

        HorizontalLayout {
            alignment: center;

            Rectangle {
                border-radius: 32px;
                background: #ffffff80;

                HorizontalLayout {
                    padding-top: 12px;
                    padding-bottom: 12px;
                    padding-left: 24px;
                    padding-right: 24px;
                    spacing: 24px;
                    alignment: center;

                    Image {
                        width: 40px;
                        height: 40px;
                        source: NowPlaying.is-playing ? @image-url("../assets/play.svg") : @image-url("../assets/pause.svg");
                    }

                    Image {
                        colorize: repeat ? white : #ffffff80;
                        width: 40px;
                        height: 40px;
                        source: @image-url("../assets/repeat.svg");
                    }

                    Image {
                        colorize: shuffle ? white : #ffffff80;
                        width: 40px;
                        height: 40px;
                        source: @image-url("../assets/shuffle.svg");
                    }
                }
            }
        }
    }
}
