import { Player } from "views/player.slint";
import { Library, LibraryModel } from "views/library.slint";
import { Song, NowPlaying } from "model.slint";
import { Format } from "util.slint";
import "fonts/Nunito.ttf";

export { NowPlaying, LibraryModel, Format }

export component MainWindow inherits Window {
    default-font-family: "Nunito";
    width: 640px;
    height: 480px;
    background: black;
    forward-focus: player;

    player := Player {}
    if NowPlaying.song.path == "": Library {}
}
