import { Song, NowPlaying } from "model.slint";
import { Player, MusicService } from "player.slint";
import { Format } from "util.slint";
import "fonts/Nunito.ttf";

export { NowPlaying, MusicService, Format }

export component MainWindow inherits Window {
    default-font-family: "Nunito";
    width: 640px;
    height: 480px;
    background: black;

    player := Player {
        autoplay: false;
    }
}
