import { Player } from "views/player.slint";
import { Library, LibraryModel } from "views/library.slint";
import { Song, NowPlaying } from "model.slint";
import { Format } from "util.slint";
import "fonts/Nunito.ttf";

export { NowPlaying, LibraryModel, Format }

export component MainWindow inherits Window {
    default-font-family: "Nunito";
    width: 640px;
    height: 480px;
    background: #411B1B;

    if NowPlaying.song.path != "": player := Player {
        init => {
            player.focus();
        }
    }
    if NowPlaying.song.path == "": library := Library {
        init => {
            library.focus();
        }
    }
}
