import { Slider, Button } from "std-widgets.slint";
import { NowPlaying, Song } from "model.slint";
import { Text } from "components.slint";
import { ProgressBar } from "progress-bar.slint";

export global MusicService {
    callback load_song(Song);
    callback play();
    callback pause();
}

export component Player {
    in-out property <NowPlaying> now-playing;
    in property <bool> autoplay;

    init => {
        debug("loading song");
        MusicService.load_song(now-playing.song);
        debug("loaded song");
        if autoplay {
            debug("autoplay");
            MusicService.play();
        } else {
            debug("no autoplay");
            MusicService.pause();
        }
    }
    
    height: 100%;
    width: 100%;

    VerticalLayout {
        padding-left: 36px;
        padding-right: 36px;
        alignment: start;

        Text {
            height: 48px;
            text: @tr("Now Playing");
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 24px;
        }

        HorizontalLayout {
            padding-top: 24px;
            padding-bottom: 36px;
            spacing: 36px;

            Rectangle {
                width: 250px;
                height: self.width;

                Image {
                    width: 100%;
                    height: 100%;
                    source: now-playing.song.cover-art; 
                }
            }

            VerticalLayout {
                spacing: 24px;
                alignment: start;

                Text {
                    text: now-playing.song.title;
                    wrap: word-wrap;
                    font-size: 32px;
                }

                Text {
                    text: now-playing.song.artist;
                    wrap: word-wrap;
                    font-size: 28px;
                }

                Text {
                    text: now-playing.song.album;
                    wrap: word-wrap;
                    font-size: 28px;
                }
            }
        }

        ProgressBar {
            progress: now-playing.progress;
            duration: now-playing.song.duration;
        }
    }
}
