import { NowPlaying, Song } from "model.slint";
import { HorizontalBox, VerticalBox, Slider } from "std-widgets.slint";

export component Player {
    callback play_song(Song);

    in-out property <NowPlaying> now-playing;

    init => {
        play_song(now-playing.song);
    }

    HorizontalBox {
        Image {
            source: now-playing.song.cover-art; 
        }

        VerticalBox {
            Text {
                text: now-playing.song.title;
            }

            Text {
                text: now-playing.song.artist;
            }

            Slider {
                minimum: 0;
                maximum: now-playing.duration;
                value: now-playing.progress * now-playing.duration;
            }
        }
    }
}
