import { Format } from "util.slint";
import { Text } from "components.slint";

export component ProgressBar inherits VerticalLayout {
    in property <int> duration;
    in property <float> progress;

    property<length> line-width: 12px;

    VerticalLayout {
        spacing: 12px;

        Rectangle {
            background: grey;
            height: line-width;
            border-radius: line-width;
            width: 100%;

            Rectangle {
                x: 0;
                background: white;
                height: line-width;
                border-radius: 12px;
                width: line-width + (progress / duration) * (parent.width - line-width * 2);
                animate width { duration: 1s; }
            }
        }

        HorizontalLayout {
            Text {
                text: Format.format-time(duration);
                font-size: 20px;
            }

            Text {
                text: "-" + Format.format-time(duration - progress);
                horizontal-alignment: right;
                font-size: 20px;
            }
        }
    }
}
